stages:
  - dps-run

.run_dps_job_base:
  stage: dps-run
  only:
    - conus-dps-w-cronjob
  tags:
    - shell
  script:
    - docker build -t ${IMAGE_TAG} -f Dockerfile .
    - echo 'docker run ${IMAGE_TAG} ${ALGO_NAME} ${BRANCH_NAME} ${USERNAME} ${QUEUE} --params ${PARAMS}'
    - docker run ${IMAGE_TAG} ${ALGO_NAME} ${BRANCH_NAME} ${USERNAME} ${QUEUE} --params ${PARAMS}

###################################
# DPS JOBS
###################################

dps-run:fire-atlas:
  extends: .run_dps_job_base
  variables:
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-nrt-dps
    BRANCH_NAME: conus-dps
    USERNAME: eorland_gee
    QUEUE: maap-dps-worker-8gb
    PARAMS: '{}'

