stages:
  - dps-run

.run_dps_job_base:
  stage: dps-run
  only:
    - primarykeyv2
    - pipelines
    - gc/pipelines/additions
  tags:
    - shell
  script: |
    #- docker build --build-arg BUILD_MAPP_PGT_ARG=$MAAP_PGT -t ${IMAGE_TAG} -f ./maap_runtime/Dockerfile .
    #- docker run ${IMAGE_TAG} ${ALGO_NAME} ${VERSION} ${USERNAME} ${QUEUE} ${MAAP_IMAGE_ENV} --params "${PARAMS}"
    #- docker images | grep 'fire-atlas-' | awk '{print $3}' | xargs docker rmi -f
    cd ./maap_runtime/
    pip install git+https://github.com/MAAP-Project/maap-py.git@develop
    python submit-dps-job.py ${ALGO_NAME} ${VERSION} ${USERNAME} ${QUEUE} ${MAAP_IMAGE_ENV} --params "${PARAMS}"

###################################
# MANUALLY RUN DPS JOBS
###################################

dps-run:fire-atlas-coordinator-manual:
  extends: .run_dps_job_base
  only:
    variables:
      - $REGIONAL
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: $ALGO_NAME
    VERSION: $VERSION_TAG
    USERNAME: $USERNAME
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: |
      $PARAMS_STRING
    # EXAMPLE: '{"regnm": "CaliTestRun", "bbox": "[-125,36,-117,42]", "tst": "[2023,6,1,\"AM\"]", "ted": "[2023,9,1,\"AM\"]"}'

###################################
# DPS JOBS
###################################
# schedulers that call these jobs at certain cron frequencies and times are located:
# https://repo.ops.maap-project.org/eorland_gee/fireatlas_nrt/-/pipeline_schedules

dps-run:fire-atalas-data-update-checker:
  extends: .run_dps_job_base
  only:
    variables:
       - $DATA_UPDATE_CHECKER
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-feds-dps-data-checker-v3
    VERSION: 0.99.0
    USERNAME: gcorradini
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: '{}'

dps-run:fire-atlas-coordinator:
  extends: .run_dps_job_base
  only:
    variables:
      - $CONUS
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME:  eis-feds-dps-coordinator-v3
    VERSION: 0.99.0
    USERNAME: gcorradini
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: '{"regnm": "CONUS_PREPROCESS_ARCHIVE", "bbox": "[-126.401171875,24.071240929282325,-61.36210937500001,49.40003415463647]", "tst": "[2022, 1, 1, \"AM\"]", "ted": "[2022, 12, 31, \"PM\"]"}'

dps-run:fire-atlas-boreal-automate-snapshot:
  extends: .run_dps_job_base
  only:
    variables:
      - $BOREAL_SNAP
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-boreal-automate-snapshot-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-borealna-nrt_snap
    VERSION: eli_global_boreal_snap_only
    USERNAME: tmccabe
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: '{}'
    #PARAMS: '{"regnm": "BOREAL_NRT_3571_DPS", "bbox": "[-169, 44, -48, 75]", "tst": "", "ted": ""}'

dps-run:fire-atlas-boreal-automate-lf:
  extends: .run_dps_job_base
  only:
    variables:
      - $BOREAL_LF
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-boreal-automate-lf-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-borealna-nrt_largefire
    VERSION: eli_global_boreal_largefire_only
    USERNAME: tmccabe
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: '{}'
    #PARAMS: '{"regnm": "BOREAL_NRT_3571_DPS", "bbox": "[-169, 44, -48, 75]", "tst": "", "ted": ""}'

dps-run:fire-atlas-lf-archive:
  extends: .run_dps_job_base
  only:
    variables:
      - $LF_ARCHIVE
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-lf-archive-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-combine-largefire-archive-v3
    VERSION: 0.99.0
    USERNAME: gcorradini
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: '{"folder_name": "WesternUS_REDO", "start": 2013, "end": 2021}'

dps-run:fire-atlas-lf-nrt:
  extends: .run_dps_job_base
  only:
    variables:
      - $LF_NRT
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-lf-archive-nrt-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-combine-largefire-nrt-v3
    VERSION: 0.99.0
    USERNAME: gcorradini
    QUEUE: maap-dps-eis-worker-32gb
    PARAMS: '{"folder_name": "CONUS_NRT_DPS"}'
