stages:
  - dps-run

.run_dps_job_base:
  stage: dps-run
  only:
    - primarykeyv2
  tags:
    - shell
  script:
    - docker build -t ${IMAGE_TAG} -f ./maap_runtime/Dockerfile .
    - docker run ${IMAGE_TAG} ${ALGO_NAME} ${VERSION} ${USERNAME} ${QUEUE} ${MAAP_IMAGE_ENV} --params "${PARAMS}"

###################################
# DPS JOBS
###################################
# schedulers that call these jobs at certain cron frequencies and times are located:
# https://repo.ops.maap-project.org/eorland_gee/fireatlas_nrt/-/pipeline_schedules

dps-run:data-update-checker:
  extends: .run_dps_job_base
  only:
    variables:
       - $DATA_UPDATE_CHECKER
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-dps-data-checker-v2
    VERSION: 1.0.0
    USERNAME: tmccabe
    QUEUE: maap-dps-worker-32gb
    PARAMS: '{}'

dps-run:fire-atlas-conus:
  extends: .run_dps_job_base
  only:
    variables:
      - $CONUS
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-dps-main-v3test
    VERSION: 0.99.3
    USERNAME: gcorradini
    QUEUE: maap-dps-worker-32gb
    PARAMS: '{"regnm": "CONUS_ARCHIVE_P_KEY", "bbox": "[-126.401171875,24.071240929282325,-61.36210937500001,49.40003415463647]", "tst": "[2022, 1, 1, \"AM\"]", "ted": "[2022, 12, 31, \"PM\"]"}'

dps-run:fire-atlas-boreal-automate-snapshot:
  extends: .run_dps_job_base
  only:
    variables:
      - $BOREAL_SNAP
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-boreal-automate-snapshot-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-borealna-nrt_snap
    VERSION: eli_global_boreal_snap_only
    USERNAME: tmccabe
    QUEUE: maap-dps-worker-128gb
    PARAMS: '{}'
    #PARAMS: '{"regnm": "BOREAL_NRT_3571_DPS", "bbox": "[-169, 44, -48, 75]", "tst": "", "ted": ""}'

dps-run:fire-atlas-boreal-automate-lf:
  extends: .run_dps_job_base
  only:
    variables:
      - $BOREAL_LF
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-boreal-automate-lf-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-borealna-nrt_largefire
    VERSION: eli_global_boreal_largefire_only
    USERNAME: tmccabe
    QUEUE: maap-dps-worker-128gb
    PARAMS: '{}'
    #PARAMS: '{"regnm": "BOREAL_NRT_3571_DPS", "bbox": "[-169, 44, -48, 75]", "tst": "", "ted": ""}'

dps-run:fire-atlas-lf-archive:
  extends: .run_dps_job_base
  only:
    variables:
      - $LF_ARCHIVE
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-lf-archive-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-combine-largefire-archive-v3test
    VERSION: 0.99.3
    USERNAME: gcorradini
    QUEUE: maap-dps-worker-32gb
    PARAMS: '{"folder_name": "WesternUS_REDO", "start": 2013, "end": 2021}'

dps-run:fire-atlas-lf-nrt:
  extends: .run_dps_job_base
  only:
    variables:
      - $LF_NRT
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-lf-archive-nrt-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-combine-largefire-nrt-v3test
    VERSION: 0.99.3
    USERNAME: gcorradini
    QUEUE: maap-dps-worker-32gb
    PARAMS: '{"folder_name": "CONUS_NRT_DPS"}'