stages:
  - dps-run

.run_dps_job_base:
  stage: dps-run
  only:
    - conus-dps
  tags:
    - shell
  script:
    - docker build -t ${IMAGE_TAG} -f Dockerfile .
    - docker run ${IMAGE_TAG} ${ALGO_NAME} ${BRANCH_NAME} ${USERNAME} ${QUEUE} ${MAAP_IMAGE_ENV}

###################################
# DPS JOBS
###################################

dps-run:fire-atlas-western-us-nrt:
  extends: .run_dps_job_base
  only:
    variables:
      - $WESTERN_US_NRT
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-nrt-dps
    BRANCH_NAME: conus-dps
    USERNAME: ashiklom
    QUEUE: maap-dps-worker-8gb


dps-run:fire-atlas-western-us-nrt-build-command-test:
  extends: .run_dps_job_base
  only:
    variables:
      - $WESTERN_US_NRT
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-nrt-dps-build-command
    BRANCH_NAME: conus-dps-build-command
    USERNAME: ashiklom
    QUEUE: maap-dps-worker-8gb

