stages:
  - dps-run

.run_dps_job_base:
  stage: dps-run
  only:
    - conus-dps
  tags:
    - shell
  script:
    - docker build -t ${IMAGE_TAG} -f ./maap_runtime/Dockerfile .
    - docker run ${IMAGE_TAG} ${ALGO_NAME} ${BRANCH_NAME} ${USERNAME} ${QUEUE} ${MAAP_IMAGE_ENV}

###################################
# DPS JOBS
###################################
# schedulers that call these jobs at certain cron frequencies and times are located:
# https://repo.ops.maap-project.org/eorland_gee/fireatlas_nrt/-/pipeline_schedules

dps-run:data-update-checker:
  extends: .run_dps_job_base
  only:
    variables:
       - $DATA_UPDATE_CHECKER
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-dps-data-checker
    BRANCH_NAME: conus-dps
    USERNAME: ashiklom
    QUEUE: maap-dps-worker-8gb

dps-run:fire-atlas-conus:
  extends: .run_dps_job_base
  only:
    variables:
      - $CONUS
  variables:
    MAAP_IMAGE_ENV: ubuntu
    IMAGE_TAG: fire-atlas-${CI_COMMIT_SHORT_SHA}
    ALGO_NAME: eis-fire-feds-nrt-dask-dps
    BRANCH_NAME: conus-dps
    USERNAME: ashiklom
    QUEUE: maap-dps-worker-32gb