[build-system]
requires = ["setuptools>=57", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fireatlas"
dynamic = ["version"]
requires-python = ">=3.10"
readme = "README.md"

# core runtime deps needed to use fireatlas as library
dependencies = [
    # compiled- installed w conda in env.yml
    "geopandas", 
    "numpy", 
    "pandas", 
    "pyarrow", 
    "pyogrio", 
    "pyproj", 
    "scikit-learn", 
    "scipy", 
    "shapely", 
    "rasterio", 
    "rtree", 
    "xarray",
    # pure python 
    "dask", 
    "distributed", 
    "fsspec", 
    # aiobotocore is imported like this due to a complex dependency issue with s3fs: 
    # https://github.com/fsspec/s3fs/issues/357
    "aiobotocore[awscli,boto3]",
    "s3fs", # should resolve to a recent version now and not get stuck at 0.4
    "pydantic", 
    "pydantic-settings", 
    "requests", 
    "tqdm", 
]

[project.optional-dependencies] 
prod = [
    "maap-py" # needed to submit jobs to MAAP
]

test = [
    "pytest", 
    "pytest-cov", 
]

dev = [
    "fireatlas[test,prod]",
    "ipykernel", 
    "folium", 
    "matplotlib", 
    "mapclassify", 
    "ruff" 
]


[tool.setuptools.packages.find]
include = ["fireatlas*"]

[tool.setuptools.package-data]
fireatlas = ["py.typed"]

[tool.setuptools.dynamic]
version = {attr = "setuptools_scm.get_version"}

[tool.setuptools_scm]
write_to = "fireatlas/_version.py"
write_to_template = "__version__ = '{version}'"

[tool.coverage.run]
omit = [
    "*/maap_runtime/*",
    "*/tests/*",
    "FireRun*.py",
]

[tool.pytest.ini_options]
addopts = "--cov=."
