[build-system]
requires = ["setuptools>=57", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fireatlas"
dynamic = ["version"]
requires-python = ">=3.10,<3.13"
description = "EIS Fire NRT DPS"
readme = "README.md"
authors = []
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: NASA/EIS/Scientific/Engineering",
]
keywords = ["eis", "fireatlas"]
dependencies = [
  "xarray",
  "pandas",
  "dask",
  "distributed",
  "geopandas<1",
  "fiona",
  "shapely",
  "fsspec",
  "s3fs>=2024.6",
  "rtree",
  "scikit-learn",
  "pyarrow",
  "pydantic-settings",
  "rasterio",
  "pyproj",
  "tqdm",
  "scalene", 
  "numpy<2", 
  "pyogrio", 
  "requests",
  "aiobotocore[boto3]==2.24.1"
]

# [project.urls]
# Homepage = "https://earth-information-system.github.io/fireatlas/docs/"
# Repository = "https://github.com/Earth-Information-System/fireatlas"
# Issues = "https://github.com/Earth-Information-System/fireatlas/issues"

[tool.setuptools.packages.find]
exclude = ["notebooks"]
include = ["fireatlas", "maap_runtime", "tests"]

[tool.setuptools.package-data]
fireatlas = ["py.typed"]

[tool.setuptools.dynamic]
version = {attr = "setuptools_scm.get_version"}

[tool.setuptools_scm]
write_to = "fireatlas/_version.py"
write_to_template = "__version__ = '{version}'"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "pytest", 
    "pytest-cov", 
    "ipykernel"
]

[tool.coverage.run]
omit = [
    "*/maap_runtime/*",
    "*/tests/*",
    "FireRun*.py",
]

[tool.pytest.ini_options]
addopts = "--cov=."
