algorithm_name: eis-feds-dps-precprocess-region-v3
algorithm_description: "create geojson for a region and maybe static source filter"
algorithm_version: 0.99.0
environment: ubuntu
repository_url: https://repo.maap-project.org/gcorradini/fireatlas_nrt.git
docker_container_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/pangeo:v3.1.4"
queue: "maap-dps-eis-worker-32gb"
run_command: "fireatlas_nrt/run_preprocess_region.sh"
build_command: ""
disk_space: "100GB"
inputs:
  config: [ ]
  positional:
  - name: regnm # name of output folder
    download: False
  - name: bbox # xmin, ymin, xmax, ymax of region bbox in lat/lon
    download: False
