algorithm_name: eis-fire-feds-dps-main-v3test
algorithm_description: "Map active fire perimeters."
algorithm_version: 1.0.0
environment: ubuntu
repository_url: https://repo.maap-project.org/gcorradini/fireatlas_nrt.git
docker_container_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/eis_feds:42644eb"
queue: "maap-dps-eis-worker-32gb"
run_command: "fireatlas_nrt/run_dps_v2.sh"
build_command: ""
disk_space: "100GB"
inputs:
  config: [ ]
  positional:
  - name: regnm # name of output folder
    download: False
  - name: bbox # xmin, ymin, xmax, ymax of region bbox in lat/lon
    download: False
  - name: tst # [year, month, day, ampm]
    download: False
  - name: ted # [year, month, day, ampm]
    download: False
  - name: export # true/false
    default: "false"
    required: false
    download: False
