algorithm_description: "Combine FEDS Largefire data into a single file."
algorithm_name: eis-fire-feds-combine-largefire-archive-v2
algorithm_version: conus-dps
environment: ubuntu
repository_url: https://repo.ops.maap-project.org/eorland_gee/fireatlas_nrt.git
docker_container_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/eis_feds:42644eb"
queue: "maap-dps-worker-32gb"
run_command: "fireatlas_nrt/run_largefire_archive.sh"
build_command: ""
disk_space: "10GB"
inputs:
  config: []
  file: []
  positional: []
