algorithm_description: "Combine FEDS Largefire data into a single file."
algorithm_name: eis-fire-feds-combine-largefire-archive-v3
algorithm_version: 1.0.0
environment: ubuntu
repository_url: https://github.com/Earth-Information-System/fireatlas.git
docker_container_url: "mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.4"
queue: "maap-dps-eis-worker-64gb"
run_command: "fireatlas_nrt/maap_runtime/run_largefire_archive.sh"
build_command: "fireatlas_nrt/maap_runtime/run_dps_build.sh"
disk_space: "10GB"
inputs:
  config: []
  positional:
  - name: folder_name # maap output folder name (basename, not actual full path)
    download: False
  - name: start # start year
    download: False
  - name: end # end year
    download: False
