algorithm_description: "Combine FEDS Largefire data into a single file."
algorithm_name: eis-fire-feds-combine-largefire-nrt-v3test
algorithm_version: 0.99.6
environment: ubuntu
repository_url: https://repo.maap-project.org/gcorradini/fireatlas_nrt.git
docker_container_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/eis_feds:42644eb"
queue: "maap-dps-worker-32gb"
run_command: "fireatlas_nrt/run_largefire_nrt.sh"
build_command: ""
disk_space: "10GB"
inputs:
  config: []
  positional:
  - name: folder_name # maap output folder name (basename, not actual full path)
    download: False
