algo_name: eis-fire-feds-quebec-dps
version: global_nrt_quebec_largefire
environment: ubuntu
repository_url: https://repo.ops.maap-project.org/eorland_gee/fireatlas_nrt.git
docker_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/eis_feds:42644eb"
queue: "maap-dps-worker-128gb"
description: "Map active fire perimeters."
run_command: "fireatlas_nrt/run_dps.sh 'QuebecSampleRun'"
build_command: ""
disk_space: "10GB"
inputs:
  config: []
  file: []
  positional: []