algorithm_description: "Data update checker"
algorithm_name: eis-feds-dps-data-checker-v3
algorithm_version: 0.99.0
environment: ubuntu
repository_url: https://repo.maap-project.org/gcorradini/fireatlas_nrt.git
docker_container_url: "mas.maap-project.org/root/maap-workspaces/base_images/pangeo:v3.1.4"
queue: "maap-dps-eis-worker-32gb"
run_command: "fireatlas_nrt/run_dps_data_checker.sh"
build_command: ""
disk_space: "10GB"
inputs:
  config: []
  file: []
  positional: []
