algorithm_description: "Map active fire perimeters."
algorithm_name: eis-fire-feds-dps-data-checker-v2
algorithm_version: conus-dps
environment: ubuntu
repository_url: https://repo.ops.maap-project.org/eorland_gee/fireatlas_nrt.git
docker_container_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/eis_feds:42644eb"
queue: "maap-dps-worker-8gb"
run_command: "fireatlas_nrt/run_dps.sh 'DataUpdateChecker'"
build_command: ""
disk_space: "10GB"
inputs:
  config: []
  file: []
  positional: []
