algorithm_description: "Map active fire perimeters."
algorithm_name: eis-conus-test
algorithm_version:  conus_dps_scalene
environment: ubuntu
repository_url: https://repo.maap-project.org/gcorradini/fireatlas_nrt.git
docker_container_url: "mas.dit.maap-project.org/root/maap-workspaces/base_images/eis_feds:42644eb"
queue: "maap-dps-worker-32gb"
run_command: "fireatlas_nrt/run_dps.sh"
build_command: ""
disk_space: "100GB"
inputs:
  config: []
  file: []
  positional: 
    - default: ''
      description: "Function name to run in FireRun"
      name: function_name
      required: true