algorithm_name: eis-feds-dps-preprocess-region-and-t-v3
algorithm_description: "do initial filtering and clustering and write to dataframe"
algorithm_version: 0.99.0
environment: ubuntu
repository_url: https://repo.maap-project.org/gcorradini/fireatlas_nrt.git
docker_container_url: "mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.4"
queue: "maap-dps-eis-worker-32gb"
run_command: "fireatlas_nrt/run_preprocess_region_and_t.sh"
build_command: "fireatlas_nrt/run_dps_build.sh"
disk_space: "100GB"
inputs:
  config: [ ]
  positional:
  - name: regnm # name of output folder
    download: False
  - name: t # [year, month, day, ampm]
    download: False
