name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: build deps
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm wheel twine

# TODO: uncomment once we have PYPI credentials in place
#      - name: build and publish to pypi
#        run: |
#          python -m build
#          twine upload dist/*
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: kick off the DPS job
        uses: Earth-Information-System/fireatlas/.github/actions/release@primarykeyv2
        with:
          maap_pgt_secret: ${{ secrets.MAAP_PGT }}

