name: data update checker

on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  data_update_checker:
    if: contains('["ranchodeluxe"]', github.actor)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: gc/github_actions

    - name: pip install fireatlas
      run: |
        pip install .

    - name: kick off the job
      run: |
        docker run \
          --env MAAP_PGT=${MAAP_PGT} \
          --env MAAP_CONF=/maap-py \
          --pull=always -u ${UID}:${DOCKER_GID} -v ${PWD}:${PWD} -w ${PWD} \
          --rm mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.4 \
          /opt/conda/envs/vanilla/bin/python maap_runtime/submit-dps-job.py \
          eis-feds-dask-coordinator-v3 \
          1.0.0 \
          gcorradini \
          maap-dps-eis-worker-64gb \
          ubuntu \
          --params '{"regnm": "", "bbox": "[]", "tst": "[]", "ted": "[]", "operation": "--data-update"}'
