name: data update checker

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  run_dps_job_v3:
    if: contains('["ranchodeluxe"]', github.actor)
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: primarykeyv2

    - name: pip install fireatlas
      run: |
        pip install .

    - name: get docker GID and set DOCKER_GID environment variable
      run: |
        echo "DOCKER_GID=$(getent group docker | cut -d: -f3)" >> $GITHUB_ENV

    - name: get current user UID and set UID environment variable
      run: |
        echo "UID=$(id -u)" >> $GITHUB_ENV

    - name: print DOCKER_GID and UID
      run: |
        echo "Docker GID: $DOCKER_GID"
        echo "User UID: $UID"

    - name: kick off the DPS job
      uses: Earth-Information-System/fireatlas/.github/actions/run-dps-job-v3@conus-dps
      with:
        algo_name: eis-fire-feds-dps-data-checker-v2
        branch_name: conus-dps
        username: tmccabe
        queue: maap-dps-eis-worker-32gb
        maap_image_env: ubuntu
        --params '{"regnm": "", "bbox": "[]", "tst": "[]", "ted": "[]", "operation": "--data-update"}'


