name: western usa nrt v3

on:
  workflow_dispatch:
  schedule:
    - cron:  '45 6,9,18,21 * * *'

jobs:
  run_dps_job_v3:
    if: false  #contains('["ranchodeluxe", "mccabete"]', github.actor)
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: primarykeyv2

    - name: pip install fireatlas
      run: |
        pip install .

    - name: get docker GID and set DOCKER_GID environment variable
      run: |
        echo "DOCKER_GID=$(getent group docker | cut -d: -f3)" >> $GITHUB_ENV

    - name: get current user UID and set UID environment variable
      run: |
        echo "UID=$(id -u)" >> $GITHUB_ENV

    - name: print DOCKER_GID and UID
      run: |
        echo "Docker GID: $DOCKER_GID"
        echo "User UID: $UID"

    - name: kick off the DPS job
      uses: Earth-Information-System/fireatlas/.github/actions/run-dps-job-v3@conus-dps
      with:
        algo_name: eis-feds-dask-coordinator-v3
        github_ref: 1.0.0
        username: gcorradini
        queue: maap-dps-eis-worker-64gb
        maap_image_env: ubuntu
        maap_pgt_secret: ${{ secrets.MAAP_PGT }}
        json_params: '{"regnm": "WesternUS", "bbox": "[-125.698046875, 31.676476158707615, -101.00078125, 49.51429477264348]", "tst": "[]", "ted": "[]", "operation": "--coordinate-all"}'


